---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, system manager, unsupported features 
summary: 已知限制确定了本产品版本不支持的平台、设备或功能、或者这些平台、设备或功能无法与产品正确交互操作。仔细审查这些限制。 
---
= 已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制确定了本产品版本不支持的平台、设备或功能、或者这些平台、设备或功能无法与产品正确交互操作。仔细审查这些限制。



== ASA r2系统

发现NetApp ASA R2系统并打开工作环境后、您将直接转到System Manager。

ASA R2系统没有其他可用的管理选项。您不能使用标准视图、也不能启用BlueXP服务。

https://docs.netapp.com/us-en/asa-r2/index.html["详细了解ASA R2系统"^]



== 集群不受支持

BlueXP不支持配置了SAML身份验证的内部ONTAP 集群。



== System Manager限制

BlueXP不支持以下System Manager功能：

* 集群设置
+
在内部ONTAP 集群上设置管理IP地址并配置管理员密码后、您可以在BlueXP中发现此集群。

* 基于角色的访问控制(仅限连接器)
+
使用Connector发现和管理内部ONTAP 集群时、不支持从System Manager进行基于角色的访问控制。在发现过程中、系统会提示您输入管理员凭据。这些凭据用于从System Manager执行的所有操作。

+
使用直接发现选项、每次打开工作环境时、系统都会提示您使用ONTAP 凭据登录。

* BlueXP备份和恢复(Cloud Backup)激活
+
要从System Manager启用BlueXP备份和恢复、集群版本必须为9.13.1。

+
如果您未使用Connector发现集群、则无法使用System Manager (高级视图)启用备份和恢复。但是、您可以直接从BlueXP在内部集群上启用备份和恢复。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["了解如何开始使用"^]

* 按需升级
+
如果集群版本为ONTAP 9.9.1或更早版本、则无法按需升级固件和软件。

+
如果您没有Connector、则无法从本地计算机进行更新、只能从可使用BlueXP访问的服务器进行更新。

* 全局搜索
* 用户界面设置

